site:
  title: OpenCPN Developer Manual
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  ocpn-dev-manual:ROOT:AboutThisManual.adoc

content:
  sources:
    - url: https://github.com/rgleason/ocpn-dev-manual
      branches: main
      edit_url: true
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: false
    - url: https://github.com/Rasbats/managed_plugins.git
      branches: asciidoc
      edit_url: false
      start_path: manual
ui:   
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: docs

runtime:
  fetch: true
