site:
  title: OpenCPN Developer Manual
  # the 404 page and sitemap files only get generated when the url property is seto
  url: http://localhost/opencpn
  start_page:  ocpn-dev-manual:ROOT:developer_guide.adoc

content:
  sources:
    - url: https://github.com/leamas/ocpn-dev-manual.git
      branches: main   
      edit_url: false
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: true
    - url: https://github.com/leamas/shipdriver_pi.git
      branches: master
      edit_url: true
ui:   
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true


