site:
  title: OpenCPN Developer Manual
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  ocpn-dev-manual:ROOT:intro-AboutThisManual.adoc

content:
  sources:
    - url: https://github.com/rgleason/ocpn-dev-manual
      branches: main
      edit_url: true
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: false
    - url: https://github.com/Rasbats/managed_plugins.git
      branches: asciidoc
      edit_url: false
      start_path: manual
ui:   
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: docs
  clean: true

runtime:
  fetch: true

asciidoc:
  attributes:
    page-resource_1_title: OpenCPN.org
    page-resource_1_url: https://www.opencpn.org/
    page-resource_2_title: User Manual
    page-resource_2_url: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
    page-resource_3_title: Github Site
    page-resource_3_url: https://github.com/opencpn/OpenCPN
    page-resource_4_title: Bugtracker
    page-resource_4_url: https://opencpn.org/flyspray/
    page-resource_5_title: Plugin Manual (WIP)
    page-resource_5_url: https://rasbats.github.io/opencpn-plugins-manual/
